version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: taiyi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: taiyi
      MYSQL_USER: taiyi
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - taiyi-network

  # 太乙应用
  taiyi-app:
    build: .
    container_name: taiyi-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taiyi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: taiyi
      SPRING_DATASOURCE_PASSWORD: 123456
      JWT_SECRET: taiyi-docker-secret-key-for-jwt-token-generation-2024
    ports:
      - "8080:8080"
      - "10000-20000:10000-20000"  # 隧道端口范围
    depends_on:
      - mysql
    networks:
      - taiyi-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  taiyi-network:
    driver: bridge
