spring:
  application:
    name: taiyi
  
  # 数据库配置 - 通过环境变量注入
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    
# JWT配置
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  
# 内网穿透配置
tunnel:
  port-range:
    start: 10000
    end: 20000
  max-connections: 1000
  heartbeat-interval: 30
  
# 日志配置
logging:
  level:
    io.github.charlie237.taiyi: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
